name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: test
        run: printenv
      
      - name: Docker login
        run: echo $CR_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
        
      - name: Build docker image
        run: docker build -t ghcr.io/aliaksandrdub/test:latest .
        
      - name: Push docker image
        run: docker push ghcr.io/aliaksandrdub/test:latest
